export {
  pageTypes,
  socialPlatforms,
  useAdminBanners,
  useAdminFooter,
  useAdminPages,
  useDeleteBanner,
  useSaveBanner,
  useSaveFooter,
  useSavePage,
  type AdminBanner,
  type AdminPage,
  type BannerInput,
  type EditableColumn,
  type EditableLink,
  type FooterInput,
  type PageInput,
  type PageType,
  type SocialPlatform,
} from './api'
